name: Update PR body with pivotal story link

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  update_pr_body:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - name: Update PR body with pivotal story link
        run: ./bin/update-pr-with-story-link '${{ github.event.pull_request.url }}' '${{ secrets.token }}'
